# -*- coding: utf-8 -*-
"""Iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R45sa7y1fLTHkR9tbhRuiGMkwnEd8fwU
"""

#Iris Dataset

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.tree import plot_tree
from sklearn.tree import DecisionTreeClassifier, export_text, export_graphviz
import pydotplus
from IPython.display import Image
import graphviz

!gdown 1FG21oBIkz6xmjKTXlqNmcsvRmpxfVv8n

columns = ['Sepal length','Sepal width','Petal length','Petal width','Class labels']
df = pd.read_csv('iris.data',names=columns)

X = df.drop("Class labels",axis=1)
Y = df["Class labels"]

#Decision Tree Classifier

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.30)
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy')
classifier.fit(X_train,Y_train)
y_pred  = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix,classification_report
print("Confusion Matrix:")
print(confusion_matrix(Y_test,y_pred))
print("------------------")
print("-------------------")
print('Classification Report:')
print(classification_report(Y_test,y_pred))

dot_data = export_graphviz(classifier, out_file=None, feature_names=X.columns, class_names=Y.unique(),
                           filled=True, rounded=True, special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data)
decision_tree_image_path = "decision_tree.png"
graph.write_png(decision_tree_image_path)
Image(decision_tree_image_path)

import seaborn as sns

cm = confusion_matrix(Y_test,y_pred)

sns.heatmap(cm,annot=True,fmt="d",cmap='magma')

plt.show

import matplotlib.pyplot as plt

categories = ['90-10', '80-20', '70-30', '60-40', '50-50']

values = [0.87, 0.93,0.96, 0.96, 0.96]

plt.plot(categories, values)

plt.xlabel('Train-Test Division')

plt.ylabel('Accuracy')

plt.title('Comparison of Accuracy')

plt.show()

#MultinomialNB

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.30)

from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB(alpha=2.5,fit_prior=True,class_prior=None).fit(X_train,Y_train)
classifier.fit(X_train,Y_train)
y_pred  = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix

print("Confusion Matrix:")
print(confusion_matrix(Y_test,y_pred))
print("------------------")
print("-------------------")
print('Classification Report:')
print(classification_report(Y_test,y_pred))

import seaborn as sns

cm = confusion_matrix(Y_test,y_pred)

sns.heatmap(cm,annot=True,fmt="d",cmap='magma')

plt.show

import matplotlib.pyplot as plt

categories = ['90-10', '80-20', '70-30', '60-40', '50-50']

values = [0.87, 0.83, 0.98, 0.96, 0.91]

plt.plot(categories, values)

plt.xlabel('Train-Test Division')

plt.ylabel('Accuracy')

plt.title('Comparison of Accuracy')

plt.show()

#GaussianNB

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.30)
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB(priors=None,var_smoothing=1e-05).fit(X_train,Y_train)
classifier.fit(X_train,Y_train)
y_pred  = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix

print("Confusion Matrix:")
print(confusion_matrix(Y_test,y_pred))
print("------------------")
print("-------------------")
print('Classification Report:')
print(classification_report(Y_test,y_pred))

import seaborn as sns


cm = confusion_matrix(Y_test,y_pred)

sns.heatmap(cm,annot=True,fmt="d",cmap='magma')

plt.show

import matplotlib.pyplot as plt

categories = ['90-10', '80-20', '70-30', '60-40', '50-50']

values = [0.93, 0.97, 0.98, 0.98, 0.93]

plt.plot(categories, values)

plt.xlabel('Train-Test Division')

plt.ylabel('Accuracy')

plt.title('Comparison of Accuracy')

plt.show()

#BernoulliNB

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.30)
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB(alpha=2.0,binarize=1.6,fit_prior=True,class_prior=None).fit(X_train,Y_train)
classifier.fit(X_train,Y_train)
y_pred  = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print("Confusion Matrix:")
print(confusion_matrix(Y_test,y_pred))
print("------------------")
print("-------------------")
print('Classification Report:')
print(classification_report(Y_test,y_pred))

import seaborn as sns

cm = confusion_matrix(Y_test,y_pred)

sns.heatmap(cm,annot=True,fmt="d",cmap='magma')

plt.show

import matplotlib.pyplot as plt

categories = ['90-10', '80-20', '70-30', '60-40', '50-50']

values = [0.80, 0.93, 0.91, 0.93, 0.93]

plt.plot(categories, values)

plt.xlabel('Train-Test Division')

plt.ylabel('Accuracy')

plt.title('Comparison of Accuracy')

plt.show()